#:schema node_modules/wrangler/config-schema.json
name = "gs-carcavelos"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "gsc-db"
database_id = "f5ced650-8f2a-4ab2-859c-8f2ecbfbddc9"
preview_database_id = "34af1ed8-7f35-4336-b669-37a0fc6996bd"
migrations_dir = "migrations"
